version: 2.1

jobs:
  test-macos:
    macos:
      xcode: "9.4.1"
    working_directory: ~/mittsu
    steps:
      - checkout

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      
      - restore_cache:
          keys:
            - mittsu-brew-v1-{{ .Branch }}
            - mittsu-brew-v1-
      - run: brew install glfw
      - save_cache:
          key: mittsu-brew-v1-{{ .Branch }}
          paths:
            - /usr/local/Homebrew
      
      - restore_cache:
          keys:
            - mittsu-bundler-v2-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "mittsu.gemspec" }}
            - mittsu-bundler-v2-{{ .Branch }}-
            - mittsu-bundler-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: mittsu-bundler-v2-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "mittsu.gemspec" }}
          paths:
            - vendor/bundle
      
      ## TEST
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rake test
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
          environment:
            MITTSU_LIBGLFW_PATH: /usr/local/lib
            MITTSU_LIBGLFW_FILE: libglfw.dylib
            MINITEST_REPORTER: JUnitReporter

      ## COLLECT RESULTS
      - store_test_results:
          path: test/reports

workflows:
  version: 2

  test:
    jobs:
      - test-macos
