name: Build on Linux
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: sudo apt-get update; sudo apt-get install cmake xorg-dev libgl1-mesa-dev
      - run: bash install-glfw-3.1.2.sh
      - run: bundle install --path vendor/bundle
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.2.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec rake test
